### PR TITLE
Fix Notices Class Static Method Error and Improve Documentation #23

### LINKED ISSUE #23: Cannot use $this in static method add() in Notices class
In `/src/Admin/Notices.php`, the static method `add()` attempts to use `$this` 
Static methods should not use $this. Either make add() a non-static method, or use a static property (e.g., self::$notices) instead.

### PR DESCRIPTION
**Pull request by alhoseany**
# Fix Notices Class Static Method Error and Improve Documentation

## Overview
This PR resolves a critical PHP error in the `Notices` class and adds comprehensive documentation for the Admin Notices functionality.

### 🐛 Bug Fix: Notices Class Static Method Error
- **File**: `src/Admin/Notices.php`
- **Issue**: The `add()` method was declared as `static` but attempted to use `$this->notices`, causing a "Cannot use '$this' in non-object context" error
- **Solution**: Removed the `static` keyword from the `add()` method to allow proper instance method behavior

**Before:**
```php
public static function add( array $args ) {
    // ... code using $this->notices
}
```

**After:**
```php
public function add( array $args ) {
    // ... code using $this->notices
}
```

### 📚 Documentation Enhancement: Admin Notices Usage
- **File**: `readme.md`
- **Added**: Complete "Admin Notices" section with usage examples
- **Includes**: 
  - Proper instantiation examples
  - Available notice types (`success`, `error`, `warning`, `info`)
  - Configuration options and parameters
  - Code examples showing best practices

### Breaking Change Notice
⚠️ **Breaking Change**: The `Notices::add()` method is no longer static. Code calling this method must be updated:

**Old Usage (No longer works):**
```php
Notices::add( $args );
```

**New Usage (Required):**
```php
$notices = new Notices();
$notices->add( $args );
```

### Benefits
- ✅ Resolves fatal PHP errors when using the Notices class
- ✅ Provides clear documentation for developers
- ✅ Maintains WordPress admin notice standards
- ✅ Enables proper instance-based notice management

## Files Changed
- `src/Admin/Notices.php` (1 line changed)
- `readme.md` (21 lines added)

## Testing
- [x] Verified `Notices` class instantiation works correctly
- [x] Confirmed `add()` method functions without errors
- [x] Validated notice rendering in WordPress admin

Closes #23

### CODE REVIEW

File: src/Admin/Notices.php [hunk 1]
```diff
@@ -38,7 +38,7 @@ public function __construct() {
 	 * @since <next-version>
 	 * @param array $args The notice arguments.
 	 */
-	public static function add( array $args ) {
+	public function add( array $args ) {
```
Comment (robincornett) [inline src/Admin/Notices.php:41]: Since the notices property is private, and the the class is instantiated by the SDK, let's please keep this `static` and update the property to be static instead.

**Review by robincornett — CHANGES_REQUESTED** [review]

File: readme.md [hunk 2]
```diff
@@ -108,3 +108,52 @@ if ( file_exists( __DIR__ . '/vendor/easy-digital-downloads/edd-sl-sdk/edd-sl-sd
...
 - `type` - `plugin` or `theme`. Not needed for plugins.
 - `weekly_check` - Optional: whether to make a weekly request to confirm the license status. Defaults to true.
+
+## Admin Notices
+
+The SDK includes a `Notices` class for displaying admin notices. The registry automatically handles instantiation, so you can use the static `add()` method directly.
+
+### Adding Notices
+
+You can add notices statically from anywhere in your code before the `admin_notices` hook fires at priority 100:
```
Comment (robincornett) [inline readme.md:118]: Let's please just show one correct example. My preference would be the one using the `admin_notices` hook.

Ideally, we will also direct them to use translation ready strings for their message, please.

**Review by robincornett — CHANGES_REQUESTED** [review]

**Review by robincornett — APPROVED** [review]
